# Site settings
title: Justin Boyer
twitter_username: theJustinLBoyer
name: Justin Boyer

# Build settings
markdown: kramdown


#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Personal Website
   url: https://sites.google.com/site/justinlboyer/
 - title: GitHub
   url: https://github.com/justinlboyer/
 - title: LinkedIn
   url: https://www.linkedin.com/in/justin-l-boyer

#Any buzzword skills you want to include
skills:
 - R
 - Matlab
 - Modeling
 - Analysis
 - Machine Learning
 - Differential Equations
 - Optimization
 - Linear Algebra
 - Collaborative Problem Solving


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Data Analyst
   start: 2017
   end: Ongoing
   employer: Motion Control Inc.
   description: I use Tableau and Python to analyze the features of prosthesis and the landscape of patients to provide a quantitative perspective for health care providers.  I develop algorithms to recommend the "best" prosthetic for patients.
 - title: Research Assistant
   start: 2008
   end: 2016
   employer: University of Utah
   description: I solve math problems, ranging from fluid flow to analyzing the type of graph configurations which admit solutions.  I use a range of techniques, but I must admit, in order to get an intuition I often approximate the problems using Matlab, R, and my new love Python.
   
#Education is required
education:
 - level: Master of Mathematics 
   date: 2017
   subject: Mathematics
   school: University of Utah  
 - level: Bachelor of Science (B.S.)
   date: 2012
   subject: Mathematics, minor Physics
   school: University of Utah  
 - level: Bachelor of Science (B.A.)
   date: 2007
   subject: Film, minor Business
   school: University of Utah

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/fa49b322df743296f38637fba421a608
   courses:
     - title: Machine Learning
       link: https://www.coursera.org/learn/machine-learning/home
       optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/topics/ml/small-icon.png
       date: Completed January, 2017 -- 96.5%
       
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013


#List of interesting Github repo/projects to include - optional
github:
 - justinlboyer/TDA-CircularValuedParameterfunzation
 - justinlboyer/avalanche
#Mobile apps section is optional
apps:
 - name: Persistent Homology Using Rips
   platform: R
   url: https://justinlboyer.shinyapps.io/persistent_homology_using_rips/
   description: An interactive demonstation of a topological data analysis technique for detecting connected components and tunnels.
 - name: Avalanche Forecaster
   platform: R
   url: https://justinlboyer.shinyapps.io/avalanche/
   description: An app that gives the probability of an avalanche occuring based on user input.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>R, Matlab</strong>: I am experienced in R and Matlab. Prior to using R and Matlab to build models, I tutored students learning these languages for 4 years. <br/><br/>
   <strong>Data Analysis</strong>: My Data Analysis experience has foundations in coursework in probability and statistics further supplemented by MOOC's in machine learning and professional development in Data Analysis.  I have applied what I learned during my 2+ years teaching by using data and my own analysis to provide targeted remediation.  Using my analysis I was able to increase the targeted students scores by over 10%.  Currently I have performed data analyst contract work while finishing my Masters.  In this role, I collaborated with the president and the marketing team to identify customer insights, verify them with statistical tests and provide summary and recommendations to management.  Additionally, I had to clean and wrangle the data prior to my analysis, which included validating the data set, uncovering and removing the fraudulent data.<br/><br/>
   <strong>Numerical Analysis</strong>: I have completed year long coursework in numerical analysis.  In this course we analysised many numerical methods, such as Regression, Finite Element, and Fast Fourier Transform.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and the research which I have undertaken in my free time, including Java, Android, Google Analytics, and Teaching Methodologies. 
   
   
