# Site settings
title: Justin Boyer
twitter_username: theJustinLBoyer
name: Justin Boyer

# Build settings
markdown: kramdown


#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Personal Website
   url: https://sites.google.com/site/justinlboyer/
 - title: GitHub
   url: https://github.com/justinlboyer/
 - title: LinkedIn
   url: https://www.linkedin.com/in/justin-l-boyer

#Any buzzword skills you want to include
skills:
 - R
 - Modelling
 - Analysis
 - Python
 - Graph Theory
 - Differential Equations
 - SQL
 - Collaborative Problem Solving


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Research Assistant
   start: 2008
   end: Ongoing
   employer: University of Utah
   description: I solve really difficult math problems, by any means necessary.
   
#Education is required
education:
 - level: Master of Mathematics 
   date: 2017
   subject: Mathematics
   school: University of Utah  
 - level: Bachelor of Science (B.S.)
   date: 2012
   subject: Mathematics, minor Physics
   school: University of Utah  
 - level: Bachelor of Science (B.A.)
   date: 2007
   subject: Film, minor Business
   school: University of Utah

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/fa49b322df743296f38637fba421a608
   courses:
     - title: Machine Learning
       link: https://www.coursera.org/learn/machine-learning/home
       optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/topics/ml/large-icon.png?auto=format&dpr=1&w=80&h=80&fit=fill&bg=FFF
       date: December, 2016
       
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013


#List of interesting Github repo/projects to include - optional
github:
 - justinlboyer/avalanche
#Mobile apps section is optional
apps:
 - name: Avalanche Forecaster
   platform: R
   url: https://justinlboyer.shinyapps.io/avalanche/
   description: An app that gives the probability of an avalanche occuring based on user input.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>R, Matlab</strong>: I am experienced in R and Matlab. Prior to using R and Matlab to build models, I tutored students learning these languages for 4 years. <br/><br/>
   <strong>Data Analysis</strong>: My Data Analysis experience stems from coursework in probability and statistics further supplemented by MOOC's in statistics and machine learning.<br/><br/>
   <strong>Numerical Analysis</strong>: I have completed year long coursework in numerical analysis.  In this course we analysised many numerical methods, such as Regression, Finite Element, and Fast Fourier Transform.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Java, Android, Google Analytics, and Teaching Methodoligies. 
   
   
